#!/bin/bash

function usage() {
	echo "Usage: $0 <assembler file>" 
	exit 1
}

if [ -z $1 ]; then
	usage
	exit 1
fi

if [ ! -f $1 ]; then
	echo "File $1 doesn't exist"
fi

nasm $1 &>/dev/null

if [ $? -ne 0 ]; then
	echo "Failed assembling file $1" >&2
fi

sh_name=${1%.*}
sh_dump=$(hexdump -C $sh_name | cut -c 10-60 | tr '\n' ' ' | sed -r 's/\s+/ /g; s/\s+$//g; s/\s/\\x/g')

echo $sh_dump
